### PR TITLE
Add support for CONSTRUCT and ASK query

### PR DESCRIPTION
**Pull request by fishinthecalculator**
The following three commits implement two new query statements ( `CONSTRUCT`, `ASK`) and enable (almost, more on this later) generic parsing of SPARQL where patterns.

1. The first commit refactors generic `where` behavior out of the select function and adds a new `where` function and a new `triples->pattern` function to compile a list of triples to a SPARQL where clause. This new function makes it easier (to a certain measure)  to implement most popular SPARQL statements such as `MINUS` or `OPTIONAL` which are implemented.

2. The second commit creates a new `construct` function implementing the SPARQL `CONSTRUCT` statement. `construct` takes a template (list of triples)  and a pattern (also list of triples) and returns a string containing the query, exactly as `select`.

3. The third commit implements the `ASK` statement with a new function `ask` that takes a list of triples and returns a string containing the query.

The current approach to parsing is generic enough that made possible to implement quite easily `MINUS` and `OPTIONAL` (and probably `UNION` would also be easy), but I'm not sure it would be enough to implement for example `FILTER` statements because then it should also be able to handle expressions. 

Before starting to implement too much in a way that I wasn't sure was solid enough, I wanted to get your feedback about these three commits. What do you think?

### CODE REVIEW

**Comment by roelj** [comment]
Thank you for implementing the `CONSTRUCT` and `ASK` statements.  I appreciate the elaborate description of the changes a lot!

1. The refactoring of `where` and the new `triples->pattern` make sense to me.  I think this is definitely a good way forward.
2. I tried to make a `construct` query and came up with this:
```
(display
 (let ((rdf (prefix "http://www.w3.org/1999/02/22-rdf-syntax-ns#")))
   (construct '((s y z))
              `((s p o)
                (s ,(rdf "type") t)))))
=>
CONSTRUCT 
{
  ?s ?y ?z .
}
WHERE 
{
  ?s ?p ?o .
  ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?t .
}
```
At first I was a bit confused, and thought about doing:
```
(construct '((s y z))
  (where '((s p o)))
```
But with this the `where` is inside the scope of the `construct` statement.  Even though that makes sense to me, it deviates from the SPARQL syntax. I realize we also don't do this with the `select` function.  What are your thoughts on this?

3. Nice!
```
(display
 (let ((rdf (prefix "http://www.w3.org/1999/02/22-rdf-syntax-ns#")))
   (ask `((s ,(rdf "type") t)))))
=>
ASK 
{
  ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?t .
}
```

Some final requests:
4. Could you add the `construct` and `ask` functions to the module exports?  We'd get this:
```
(define-module (sparql lang)
  ...
  #:export (prefix select construct ask insert-data delete-data create))
```

5. It would be nice to add some examples to the documentation (`doc/guile-sparql.texi`).  Would you like to give that a try?

I'll wait for the addition of `construct` and `ask` functions to the module exports before merging this pull request.

Thank you for your time and effort!

**Comment by fishinthecalculator** [comment]
Apologies for the delay. I added the `construct`and `ask` functions to the exports and I added a small example of how to use the new `construct` function to the documentation [here](https://github.com/fishinthecalculator/guile-sparql/tree/documentation). 

If you could have a look and share your feedback, I can update the example and add another one for the `ask` function.

About 2. I don't understand in which way are we deviating from the standard, please bear in mind that I'm a bit of a novice both to Guile and SPARQL, so if you could elaborate I can definitely fix any deviance from the SPARQL standard. Also feel free to contact me by email if you prefer communicating that way.

**Comment by roelj** [comment]
Thank you for adding `construct` and `ask` to the module exports.  The example in the documentation also looks good.  Would you like to add it to the pull request?

About 2:  Let's move forward with the current way, and possibly change to a slightly different syntax later.

**Comment by fishinthecalculator** [comment]
I added an example with the ask query, I believe now we could be ready to merge. If you have any feedback please let me know!

**Comment by roelj** [comment]
Thanks a lot!

**Pull request merged**
